build:
    environment:
        php:
            version: '7.0'

    tests:
        override:
            -
                coverage:
                    file: coverage-clover.xml
                    format: coverage-clover

before_commands:
    - "composer install"

checks:
    php:
        excluded_dependencies:
            - webonyx/graphql-php
