build:
    environment:
        php:
            version: '7.0'
    tests:
        override:
            -
                command: phpunit --coverage-clover=coverage-file
                coverage:
                    file: coverage-file
                    format: php-clover

before_commands:
    - "composer install"

checks:
    php:
        excluded_dependencies:
            - webonyx/graphql-php
