language: php

php:
  - '5.6'
  - '7.0'
  - nightly

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover ./coverage-clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage-clover.xml
