language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

install:
  - yes | pecl install -f ast mongodb xdebug
  - composer install

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage-clover.xml

branches:
  only:
    - master
