version: '3'
services:
  api:
    container_name: siler_example_graphql
    image: leocavalcante/dwoole:dev
    volumes:
      - ../../:/app
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      WATCH_DIR: /app/examples/graphql
      ENTRY_POINT_FILE: /app/examples/graphql/index.php